version: '3'

services:
  reverse-proxy:
    image: traefik:1.7-alpine
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ~/data/traefik/acme.json:/acme.json
networks:
  web:
    external: true
